### ISSUE TITLE
is the nuget package dependancy on anglesharp correct version

### ISSUE THREAD

**Issue by mcshaz** [mganss/HtmlSanitizer#78]
I downloaded the nuget package 3.2.105 (which downloaded AngleShap 0.9.6) & ran the simple test
```C#
var san = new Ganss.XSS.HtmlSanitizer();
const string benign = "<p class='para'>benign string</p>";
Assert.AreEqual(benign,san.Sanitize(benign));
```
returned
```
Test method Hearts4Kids.Tests.LibraryTests.Sanitizer.TestXSSSanitizer threw exception: 
System.IO.FileLoadException: Could not load file or assembly 'AngleSharp, Version=0.9.7.21214, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ---> System.IO.FileLoadException: Could not load file or assembly 'AngleSharp, Version=0.9.6.41832, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```
updated the version of AngleSharp to 0.9.7 (latest stable) & test rerun returned:

```
Result StackTrace:	
at Ganss.XSS.HtmlSanitizer.CreateParser()
   at Ganss.XSS.HtmlSanitizer.Sanitize(String html, String baseUrl, IMarkupFormatter outputFormatter)
   at Hearts4Kids.Tests.LibraryTests.Sanitizer.TestXSSSanitizer() in C:\Users\OEM\Documents\Visual Studio 2015\Projects\Hearts4Kids\Hearts4Kids.Tests\LibraryTests\Sanitizer.cs:line 14
Result Message:	
Test method Hearts4Kids.Tests.LibraryTests.Sanitizer.TestXSSSanitizer threw exception: 
System.MissingMethodException: Method not found: 'Void AngleSharp.Configuration..ctor(System.Collections.Generic.IEnumerable`1<System.Object>, System.Globalization.CultureInfo)'.
```

**Comment by mcshaz** [comment]
sorry I had tried what I thought was a clean install, but a second clean install fis=xed the problem - the dependent assemblies are obviously correctly specified.

**Comment by mganss** [comment]
If you want to use AngleSharp 0.9.7 you have to use 3.3.128-beta. 3.2.105 does not work with 0.9.7 (see #76).
